#DOCKERFILE TO CREATE DOCKER CONTAINER FOR HOSTING MULE4 APPLICATIONS

#INCLUDING CONTAINER DEPENDENCIES
FROM alpine
FROM openjdk:8

#DEFINING BASIC ENVIRONMENT VARIABLES
ENV BUILD_DATE=10202021
ENV MULE_HOME=/opt/mule
ENV MULE_RUNTIME_ARCHIVE=mule-enterprise-standalone-4.4.0.zip
ENV MULE_RUNTIME_FOLDER=mule-enterprise-standalone-4.4.0
ENV SAMPLE_APP=hello-mule.jar
ENV DOMAIN_APP=docker-mule-common-domain-app.jar



#EXTRACT MULE RUNTIME
RUN mkdir mulezip
RUN ls -la
COPY ${MULE_RUNTIME_ARCHIVE} /mulezip
RUN cd /mulezip && ls -la
RUN cd ../opt && unzip /mulezip/${MULE_RUNTIME_ARCHIVE} && ls -la

#PREPARE MULE_HOME DIRECTORY
RUN mv /opt/${MULE_RUNTIME_FOLDER} ${MULE_HOME}

#SET PERMISSION
RUN chmod 777 ${MULE_HOME}/bin/mule
RUN chmod 777 ${MULE_HOME}/bin/launcher

#REMOVE MULE RUNTIME ARCHIVE FILE
RUN rm /mulezip -r

#START MULE RUNTIME
CMD ["/opt/mule/bin/mule"]

#EXPOSE PORT
EXPOSE 8081

#COPY MULE DOMAIN APP AND SAMPLE MULE4 APP
COPY ${DOMAIN_APP} ${MULE_HOME}/domains
COPY ${SAMPLE_APP} ${MULE_HOME}/apps